//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Academia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoID { get; set; }
        public Nullable<int> InscripcionID { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Estado { get; set; }
    
        public virtual Inscripcion Inscripcion { get; set; }
    }
}
